Speed multiphrase
UAlbertaALTLab/morphodict-backend pull request #18
Opened 2023-05-31 06:49 UTC by M1Al3x

2023-05-31 20:26 UTC, pranjal080598 requested changes

2023-06-01 01:36 UTC, M1Al3x commented on src/API/search/cvd_search.py
Prints do not have any major significance for users. Antti mentioned that he wants the backend to work even faster, so it is useful to leave it for now to keep track of speed perfomance

2023-06-01 01:37 UTC, M1Al3x commented on Pipfile
Perhaps, you are right. However, I am pretty sure that it is almost impossible to forget two packages codecov and nb_black

2023-06-01 01:41 UTC, M1Al3x commented on src/views.py
What have I done for increasing speed performance? In the first place, I've compared codes of the backend and morphodict. Then, I decided to take a look at the part of the code, which leads to the performance of 5-6 seconds instead of 1. It appeared to be fetching of single recording. The code seemed to me somewhat weird and I decided to test what it changes. I wrote a script to compare input and output of the function and figured out that it changes NOTHING. What we get into the function is eventually its output. I compared the results of morphodict with morphodict-backend, and they were matching. You can test it yourself.

2023-06-01 17:13 UTC, pranjal080598 approved these changes

2023-06-02 22:05 UTC, merged